# Generated by Django 5.2.7 on 2025-10-15 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20, unique=True, verbose_name='Versão')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('data_vigencia', models.DateTimeField(verbose_name='Data de Vigência')),
                ('ativa', models.BooleanField(default=False, verbose_name='Ativa')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Política de Privacidade',
                'verbose_name_plural': 'Políticas de Privacidade',
                'ordering': ['-data_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('termos_uso', 'Termos de Uso'), ('politica_privacidade', 'Política de Privacidade'), ('marketing', 'Comunicações de Marketing'), ('cookies', 'Uso de Cookies'), ('dados_pessoais', 'Tratamento de Dados Pessoais')], max_length=50, verbose_name='Tipo de Consentimento')),
                ('consentido', models.BooleanField(default=False, verbose_name='Consentido')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('data_consentimento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Consentimento')),
                ('data_revogacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Revogação')),
                ('versao_termos', models.CharField(default='1.0', max_length=20, verbose_name='Versão dos Termos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Consentimento LGPD',
                'verbose_name_plural': 'Consentimentos LGPD',
                'ordering': ['-data_consentimento'],
                'indexes': [models.Index(fields=['usuario', 'tipo'], name='core_consen_usuario_46cf28_idx'), models.Index(fields=['data_consentimento'], name='core_consen_data_co_a3fe0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAcessoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('leitura', 'Leitura'), ('criacao', 'Criação'), ('atualizacao', 'Atualização'), ('exclusao', 'Exclusão'), ('exportacao', 'Exportação')], max_length=20, verbose_name='Ação')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='Valor Novo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data do Acesso')),
                ('usuario_operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso_operador', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('usuario_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso_titular', to=settings.AUTH_USER_MODEL, verbose_name='Titular dos Dados')),
            ],
            options={
                'verbose_name': 'Log de Acesso a Dados',
                'verbose_name_plural': 'Logs de Acesso a Dados',
                'ordering': ['-data_acesso'],
                'indexes': [models.Index(fields=['usuario_titular', 'data_acesso'], name='core_logace_usuario_2c2068_idx'), models.Index(fields=['usuario_operador', 'data_acesso'], name='core_logace_usuario_4cfeb7_idx'), models.Index(fields=['modelo', 'acao'], name='core_logace_modelo_c78866_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acesso', 'Acesso aos Dados'), ('correcao', 'Correção de Dados'), ('anonimizacao', 'Anonimização'), ('exclusao', 'Exclusão de Dados'), ('portabilidade', 'Portabilidade'), ('informacao', 'Informações sobre Tratamento'), ('revogacao', 'Revogação de Consentimento')], max_length=20, verbose_name='Tipo de Solicitação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta')),
                ('arquivo_resposta', models.FileField(blank=True, null=True, upload_to='lgpd/solicitacoes/%Y/%m/', verbose_name='Arquivo de Resposta')),
                ('ip_solicitacao', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Solicitação')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_processadas', to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_dados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Solicitação de Dados',
                'verbose_name_plural': 'Solicitações de Dados',
                'ordering': ['-data_solicitacao'],
                'indexes': [models.Index(fields=['usuario', 'status'], name='core_solici_usuario_833336_idx'), models.Index(fields=['data_solicitacao'], name='core_solici_data_so_46e5db_idx')],
            },
        ),
    ]
