# Generated by Django 5.2.7 on 2025-10-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado de frete para este pedido', max_digits=10),
        ),
    ]
