# Generated by Django 5.2.7 on 2025-10-15 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_valor_frete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('pix', 'Pix'), ('boleto', 'Boleto Bancário')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transacao_id', models.CharField(blank=True, max_length=64)),
                ('codigo_confirmacao', models.CharField(blank=True, help_text='Código retornado pelo provedor de pagamento', max_length=128)),
                ('mensagem_retorno', models.TextField(blank=True)),
                ('cartao_final', models.CharField(blank=True, max_length=4)),
                ('nome_portador', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
