# Generated by Django 5.2.7 on 2025-10-15 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDesejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_desejos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item da Lista de Desejos',
                'verbose_name_plural': 'Lista de Desejos',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'produto')},
            },
        ),
    ]
