# Generated by Django 5.2.7 on 2025-10-15 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(choices=[('google', 'Google')], max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_sociais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Social',
                'verbose_name_plural': 'Contas Sociais',
                'ordering': ['-criado_em'],
                'unique_together': {('provedor', 'external_id')},
            },
        ),
    ]
